### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [artclarke/xuggle-xuggler#15]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/xuggle/xuggle-xuggler/blob/694de7a701b9bd5434d776464a31395b1611e289/csrc/com/xuggle/Main.cpp#L8)" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main) so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706)?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www-h.eng.cam.ac.uk/help/importedHTML/languages/C++/Thinking_in_C++/tic0255.html#Heading680) like they are described by Bruce Eckel?

**Comment by artclarke** [comment]
Because the Xuggler API has to cross language barriers (i.e. Java to C++) the API must be written so as not to propagate exceptions.  Each Xuggler API call implementation has a try-catch loop that catches C++ exceptions, generates a Java exception if running inside a JVM, and returns a negative code if not.

Because of this, any exception propagating out of a Xuggler call is an error in the API, and my main program does not have try {} catch {} clauses in it because it should never be necessary.

I hope that answers your question.
